/// Operation Request or Response.
Class HS.FHIR.vR4.Model.Resource.Parameters Extends HS.FHIR.vR4.Model.Base.Resource [ Not ProcedureBlock ]
{

/// BackboneElement
/// <p>
/// Operation Parameter.
Property parameter As List Of HS.FHIR.vR4.Model.Element.Parameters.parameter(XMLNAME = "parameter", XMLPROJECTION = "ELEMENT");

Parameter ELEMENTQUALIFIED = 1;

Parameter XMLNAME = "Parameters";

Parameter XMLPROJECTION = "ELEMENT";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Parameters";

}
